#!/usr/bin/env bash
# Usage: ./process_webp.sh
# Converts photos from photos_orig/${folder} to photos/${folder}/400|800|1600/
# and writes 1600px dimensions to _data/photo_dimensions.yml.

set -euo pipefail

cd "$(dirname "$0")"

if command -v magick >/dev/null 2>&1; then
  IM_CMD=(magick)
elif command -v convert >/dev/null 2>&1; then
  IM_CMD=(convert)
else
  echo "Error: ImageMagick binary not found in PATH (expected 'magick' or 'convert')." >&2
  exit 1
fi

if command -v identify >/dev/null 2>&1; then
  IDENTIFY_CMD=(identify)
elif command -v magick >/dev/null 2>&1; then
  IDENTIFY_CMD=(magick identify)
else
  echo "Error: ImageMagick identify binary not found in PATH (expected 'identify' or 'magick identify')." >&2
  exit 1
fi

# Define folders to process
folders=("appart" "gite0" "gite1")
dimensions_out="_data/photo_dimensions.yml"
dimensions_tmp="${dimensions_out}.tmp"

mkdir -p "$(dirname "$dimensions_out")"
{
  echo "# Generated by process_webp.sh. Do not edit manually."
  echo "# Refresh with process_webp.sh only when the underlying photo set changes."
  echo "# Avoid regenerating for unrelated tooling/version changes to prevent noisy diffs."
} > "$dimensions_tmp"

for fold in "${folders[@]}"; do
  in_dir="photos_orig/${fold}"
  out_dir="photos/${fold}"

  echo "Processing folder: ${fold}"

  # Skip if input directory doesn't exist
  if [ ! -d "$in_dir" ]; then
    echo "  Warning: ${in_dir} does not exist, skipping..."
    continue
  fi

  # Create output directories
  mkdir -p "$out_dir"/400 "$out_dir"/800 "$out_dir"/1600
  echo "${fold}:" >> "$dimensions_tmp"

  shopt -s nullglob
  photo_count=0
  for f in "$in_dir"/*.[Jj][Pp][Gg] "$in_dir"/*.[Jj][Pp][Ee][Gg]; do
    base=$(basename "$f")
    name="${base%.*}"

    echo -n "  ${name} "

    "${IM_CMD[@]}" "$f" -auto-orient -strip -resize 400x  -quality 80 "$out_dir/400/${name}-400.webp"
    "${IM_CMD[@]}" "$f" -auto-orient -strip -resize 800x  -quality 80 "$out_dir/800/${name}-800.webp"
    "${IM_CMD[@]}" "$f" -auto-orient -strip -resize 1600x -quality 80 "$out_dir/1600/${name}-1600.webp"

    read -r width height < <("${IDENTIFY_CMD[@]}" -format '%w %h\n' "$out_dir/1600/${name}-1600.webp")
    {
      echo "  ${name}:"
      echo "    width: ${width}"
      echo "    height: ${height}"
    } >> "$dimensions_tmp"

    echo "✓"
    photo_count=$((photo_count + 1))
  done
  shopt -u nullglob

  echo "  Processed ${photo_count} photos in ${fold}"
  echo ""
done

mv "$dimensions_tmp" "$dimensions_out"

echo "Wrote ${dimensions_out}"
echo "All folders processed successfully!"
